apiVersion: "v1"
kind: "List"
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: "jenkins-main-demo"
    labels:
      app: "jenkins-main"
      version: "lts"
      group: "jenkins"
    namespace: "jenkins"
  spec:
    replicas: 1
    selector:
        matchLabels:
          app: "jenkins-main"
          version: "lts"
          group: "jenkins"
    template:
      metadata:
        labels:
          app: "jenkins-main"
          version: "lts"
          group: "jenkins"
      spec:
        containers:
          - name: "jenkins-main-demo"
            image: "yosoyvilla/jenkins-main:lts"
            imagePullPolicy: "IfNotPresent"
            env:
              - name: JAVA_OPTS
                value: -Djenkins.install.runSetupWizard=false
            ports:
              - name: http-port
                containerPort: 8080
              - name: jnlp-port
                containerPort: 50000
            volumeMounts:
              - name: jenkins-home
                mountPath: "/var/jenkins_home"
        volumes:
          - name: jenkins-home
            persistentVolumeClaim:
              claimName: "jenkins-volume-claim"
              readOnly: false
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      app: "jenkins-main"
      version: "lts"
      group: "jenkins"
    namespace: "jenkins"
    name: "jenkins-main-service"
  spec:
    ports:
    - name: "http"
      port: 80
      targetPort: 9090
    - name: "jnlp"
      port: 50000
      targetPort: 50000
    selector:
      app: "jenkins-main"
      version: "lts"
      group: "jenkins"
    type: "ClusterIP"
- apiVersion: "extensions/v1beta1"
  kind: "Ingress"
  metadata:
    labels:
      app: "jenkins-main"
      version: "lts"
      group: "jenkins"
    namespace: "jenkins"
    name: "jenkins-main-ingress"
  spec:
    rules:
    - host: "jenkins"
      http:
        paths:
        - backend:
            serviceName: "jenkins-main-service"
            servicePort: 80
          path: "/"
